# Autogenerated by nbdev

d = { 'settings': { 'branch': 'trunk',
                'doc_baseurl': '/arrow',
                'doc_host': 'https://ImAKappa.github.io',
                'git_url': 'https://github.com/ImAKappa/arrow',
                'lib_path': 'arrow'},
  'syms': {}}
